version: '3.9'
services:
  auth-service:
    build: .
    working_dir: /backend
    command: uvicorn services.auth_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
  assessments-service:
    build: .
    working_dir: /backend
    command: uvicorn services.assessments_service:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
  trackers-service:
    build: .
    working_dir: /backend
    command: uvicorn services.trackers_service:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
