version: '3.9'
services:
  idp-service:
    build: .
    working_dir: /backend
    command: uvicorn services.idp_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  auth-service:
    build: .
    working_dir: /backend
    command: uvicorn services.auth_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
  assessments-service:
    build: .
    working_dir: /backend
    command: uvicorn services.assessments_service:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
  trackers-service:
    build: .
    working_dir: /backend
    command: uvicorn services.trackers_service:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
  gamification-service:
    build: .
    working_dir: /backend
    command: uvicorn services.gamification_service:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
  journeys-service:
    build: .
    working_dir: /backend
    command: uvicorn services.journeys_service:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
  nlp-service:
    build: .
    working_dir: /backend
    command: uvicorn services.nlp_service:app --host 0.0.0.0 --port 8006
    ports:
      - "8006:8006"
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - idp-service
      - auth-service
      - assessments-service
      - trackers-service
      - gamification-service
      - journeys-service
      - nlp-service
