version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:80"
      - "8001:8001"
    environment:
      - FRONTEND_ENV=
      - SECRET_KEY=changeme
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
